server:
  port: 5145
  pprof-port: 9122
  trackRoots: [ "http://127.0.0.1:5143/" ]
  ipfsClusterAddresses: [ "http://127.0.0.1:9094/" ]
  ipfsAddresses: [ "http://127.0.0.1:8081/" ]
  gatewayTimeout: 250
  maxExecTime: 60
  #支持指定域上传 combine , bfs,rfs
  uploadFieldModel: rfs
  rateLimitMax: 1000
  #上传限速1M
  uploadLimitRate: 10
  #下载限速1M
  downloadLimitRate: 10
  dataPath: afs_data
  #content-type json address:Pull configuration
  contentTypeAddr: ""
  bfsCopies: 3
  #上传限文件大小10M
  uploadLimitSize: 10
  #使用域rfs 或者 bfs,只用于下载，查询
  useField: rfs
  #性能监控+prometheus
  pprof: true
  chainStorageApiBaseAddress: http://127.0.0.1:8821
  carFileGenerationPath: ./temp/carfile
  carFileShardingThreshold: 104857600



leveldb:
  openpath: ./afs_data/datafile

logger:
  mode: debug
  level: info
  isOutPutFile: false
  maxAgeDay: 7
  rotationTime: 1
